default_platform(:android)

platform :android do

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end


  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
increment_version_code(
        gradle_file_path: "app/build.gradle",
        #ext_constant_name: "test"
        #app_folder_name:"app"
  )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


desc 'Deploy a new internal version to the Google Play Store'
  lane :internal do
  # automate the generaing signed apk using prep-key where you find config
  # for signing
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    supply(
      track: 'internal',
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH].to_s
    )
  end

end